src/main.c

(#5) Unhardcode schedule.json

---

.github/workflows/ci.yml
src/main.c
src/schedule.c
src/schedule.h

(#4) Implement /today_stream

---

src/main.c
src/rest_map_template.h.tt
src/schedule.c
src/schedule.h

(#9) Introduce /next_stream endpoint

---

src/json.c
src/json.h
src/json_test.c

 (#18) implement parse_json_number

---

src/json.c
src/json_test.c
src/s.h

(#19) Implement parse_json_string

---

src/json.c

(#28) Refactor parse_json_number with chop

---

src/json.c
src/json.h
src/json_test.c
src/memory.h

Fair warning: I have no prior experience in C.

Implement parse_json_array - fixes #20

---

src/json.c
src/json.h
src/json_test.c

(#21) implement parse_json_object

---

.gitignore
Makefile
src/json.c
src/json_check.c
src/json_test.c
src/s.h

Some json parsing fixes after testing with https://github.com/nst/JSONTestSuite

---

.github/workflows/ci.yml
.gitmodules
Makefile
src/json.c
src/json.h
src/main.c
src/rest_map_template.h.tt
src/schedule.c
src/schedule.h

(#23) Migrate skedudle to tzozen library

---

src/json.h
src/main.c
src/s.h
src/schedule.c

(#44) Implement json_as_schedule

---

src/json.c
src/json.h
src/main.c
src/s.h

(#42) Implement event_as_json

---

src/schedule.c

(#47) implement parse_schedule_cancelled_events

---

src/main.c
src/schedule.c
src/schedule.h

(#51) Implement json_as_event

---

src/main.c
src/s.h

(#43) fix serve_rest_map

---

public/index.html
public/index.js
src/main.c

(#56) Serve all file from ./public/ automatically

---

src/main.c

They create more problems than solve

Remove file path basic static routes

---

public/index.html
public/index.js
public/main.css
src/main.c

(#55) Port majority of look-and-feel from the legacy app

---

public/index.js
src/main.c

(#66) Compute human readable time diff on the frontend

---

public/index.js
src/main.c

(#63) Render a couple of past events

---

public/index.js
src/main.c

(#70) Introduce Day off cell for days when there are no streams
